### ISSUE TITLE
Global symbol "$scur" requires explicit package name

### ISSUE THREAD

**Issue by Commifreak** [tatref/nagios-scripts#1]
Just trying to setup with Nagios Core 4.0.8 on Ubuntu 14.04:

```
./check_haproxy
Global symbol "$scur" requires explicit package name at ./check_haproxy line 186.
Execution of ./check_haproxy aborted due to compilation errors.
```

Did I missed something?

**Comment by Commifreak** [comment]
Temporarily fixed by putting our $scur; above $perfdata .=

```
@185:

    if ($data[$slim]) {
        our $scur;
        $perfdata .= sprintf "%s-%s=%u;%u;%u;0;%u;", $data[$pxname], $data[$svname], $data[$scur], $swarn * $data[$slim] / 100, $scrit * $data[$slim] / 100, $data[$slim];

        # Check current session # against limit
        # our $scur;
```

**Comment by khomutoff** [comment]
Its better to put $scur and $slim to the section above:

``` perl
@166
# Variables I will use from here on:
our $pxname;
our $svname;
our $status;
our $slim;
our $scur;
```

**Comment by tatref** [comment]
Thank you both for your contribution,

Is it better to use `our` over `my`? My understanding (I'm definitely not a Perl pro) is that `my` should be used for local variables, which seems to be the case here.

**Comment by khomutoff** [comment]
Declaring a variable with `our` allows you to predeclare variables in order to use them under `use strict` without getting compile errors.
