### ISSUE TITLE
NRPE: Unable to read output

### ISSUE THREAD

**Issue by Commifreak** [tatref/nagios-scripts#2]
NRPE shows, that it is unable to read output.

Configured as:

```
command[check_haproxy]=/usr/local/nagios/libexec/check_haproxy -s /run/haproxy/admin.sock -w 75 -c 90
```

Running manually returns:

```
Check haproxy OK - checked 12 proxies.|fpm28-FRONTEND=0;7500;9000;0;10000;fpm28-QLB-WWWDMZ-FPM1=0;2250;2700;0;3000;fpm28-QLB-WWWDMZ-FPM2=0;2250;2700;0;3000;fpm28-BACKEND=0;7500;9000;0;10000; and so on...
```

Did I also missed something here? :)

**Comment by Commifreak** [comment]
Solved: The provided socket was not readable by nagios user...

**Comment by tatref** [comment]
I will add a check on the file, to prevent that kind of issues. This is basically due to `die` writing to `stderr`, but NRPE is only getting stdout.

Thanks for reporting!
